#!/bin/bash
echo preparing to push to repo

echo performing git add .
git add .

echo enter a good commit message =]
read commit_msg

git commit -m '$commit_msg'


echo pushing to master
git push




